### ISSUE TITLE
[RFE] Add tolerations for node-role.kubernetes.io/etcd=:NoExecute

### ISSUE THREAD

**Issue by mikekuzak** [flatcar/flatcar-linux-update-operator#205]
## Current situation

If the node Role is [Control Plane, Etcd] two labels are applied: 
```
node-role.kubernetes.io/control-plane=:NoSchedule 
node-role.kubernetes.io/etcd=:NoExecute
```

In that case the reboot-operation doesn't get scheduled on these nodes.
Could we support that scenario too, or what would be the right override place for this ? 

Thanks
Michal

**Comment by mikekuzak** [comment]
Ok, I created a patch override: 
```
   yq eval '.patchesStrategicMerge += ["update-agent-patch.yaml"]' -i examples/deploy/kustomization.yaml
```

update-agent-patch.yaml
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: flatcar-linux-update-agent
  namespace: reboot-coordinator
spec:
  template:
    spec:
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
```

This works.
